---
title: "Multi-species indicators"
author: "Emily Dennis"
date: "31 March 2020"
output: 
    html_document:
     toc: true
     toc_float: true
     code_folding: "hide"
---

Source functions required
```{r source functions eval=FALSE}
source("workshop_functions.R")
```


Read in collated indices for 2 species and filter to one BMS
```{r eval=FALSE}
bms <- "UKBMS"
co_index <- rbind(readRDS("my_code/bms_workshop_data/Maniola_jurtina_co_index_boot.rds"),
                  readRDS("my_code/bms_workshop_data/Polyommatus_icarus_co_index_boot.rds"))
co_index <- co_index[BMS_ID == bms]
```

Convert to log 10 collated indices (TRMOBS) 
```{r eval=FALSE}
co_index[, LOGDENSITY:= log(COL_INDEX)/log(10)][, TRMOBS := LOGDENSITY - mean(LOGDENSITY) + 2, by = .(SPECIES, BOOTi)]
```

Calculate and plot the indicator, where the confidence interval is based on the bootstraps
```{r eval=FALSE}
# Generate the indicator for real data
msi <- produce_indicator0(co_index[BOOTi == 0])
# Generate an indicator for each bootstrap
msi_boot <- produce_indicators_boot(co_index[BOOTi > 0])
# Add confidennce interval to indicator based on quantiles from the bootstraps
msi <- add_indicator_CI(msi, msi_boot)

ggplot(msi, aes(year, indicator))+
  theme(text = element_text(size = 14))+
  geom_ribbon(aes(ymin = LOWsmooth1, ymax = UPPsmooth1), alpha=.2, fill = "blue")+
  geom_point(color = "blue")+
  geom_line(aes(y = SMOOTH), color = "blue")+
  ylim(c(0, max(200,max(msi$UPPsmooth1))))+
  ggtitle(paste("Example indicator for", bms, "based on two species"))

```

Calculate the indicator trend including confidence interval from the bootstraps
```{r eval=FALSE}
msi_trend <- estimate_ind_trends(msi, msi_boot)
msi_trend
```



