---
title: "Calculating butterfly trends, indexes and indicators"
author: "Reto Schmucki, Emily Dennis, David Roy and Chris Van Swaay"
date: "April 1^st^, 2020"
output:
  html_document:
    toc: true
    toc_float: true
---

<br>

### Motivation

In the ABLE project new tools have been developed to make it easier for regional and national coordinators of Butterfly Monitoring Schemes to calculate indexes and trends as well as build indicators. This workshop will focus on the background of the method and learning how to use the tools. This workshop is open by invitation only to all co-ordinators of European Butterfly Monitoring Schemes as well as other people actively involved in the analysis and assessment of butterfly monitoring.

<br>

### Schedule

| Time         | Topic                                                                 | Instructor    |
|--------------|-----------------------------------------------------------------------|---------------|
|9:30  - 9:40  | login to virtual workshop (Zoom meeting)                              | David         |
|9:40  - 10:00 | Introduction and participant presentation                             | Chris         |
|10:00 - 11:00 | [BMS and count data in R, data wrangling and mapping](data_wrangling.html) | Reto     |
|Break         |                                                                       |               |
|11:15 - 12:15 | [Modelling Butterfly Abundance (GAI)](flight_curve_presentation.html) | Emily         |
|Lunch         |                                                                       |               |
|13:30 - 14:30 | [Flight curve](flight_curve_computing.html) and [Site & collated indices](site_indices.html)   | Reto          |
|Break         |                                                                       |               |
|14:45 - 15:45 | [Trends](species_trends.html) and [Multi-Species Indices](multispecies_indicators.html)   | Emily  |
|Break         |                                                                       |               |
|Q&A (30 min)  |                                                                       | Reto, Emily, David & Chris |
|              |                                                                       |               |


**Each session will be structured with a short presentation, a guided example and an exercise for participant to practice.**

<br>

## Before the workshop

<br>

### Computer and software

- Install **R** software from <a href="https://cran.r-project.org/"> CRAN</a>
- Install **RTools** from <a href="https://cran.r-project.org/bin/windows/Rtools/" >CRAN</a>
- Install **RStudio Desktop** (optional) <a href="https://rstudio.com/products/rstudio/download/#download"> RStudio</a>
- Install R packages

``` {r eval=FALSE, echo = TRUE}
install.packages("data.table")
install.packages("speedglm")
install.packages("devtools")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("plyr")
install.packages("sf")
install.packages("raster")
install.packages("rasterVis")
install.packages("tmap")
## rbms from GitHub
devtools::install_github("RetoSchmucki/rbms")

```
<br>

#### Download Data
<a href="https://filedn.com/l4iF16owVCHBm81sGhdrcpX/bms_workshop_data.zip"><b>WORKSHOP DATA</b></a>

<br>

#### Reading

**Dennis, E. B.**, Morgan, B. J. T., Freeman, S. N., Brereton, T. M., & Roy, D. B. (2016). A generalized abundance index for seasonal invertebrates. Biometrics, 72(4), 1305–1314. doi: 10.1111/biom.12506

<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/biom.12506" target="_blank"><b>ACCESS</b></a>

**Schmucki, R.**, Pe’er, G., Roy, D. B., Stefanescu, C., Van Swaay, C. A. M., Oliver, T. H., … Julliard, R. (2016). A regionally informed abundance index for supporting integrative analyses across butterfly monitoring schemes. Journal of Applied Ecology, 53(2), 501–510. doi: 10.1111/1365-2664.12561

<a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.12561" target="_blank"><b>ACCESS</b></a>